### ISSUE TITLE
When I set setsecure to true it gives Serialization error

### ISSUE THREAD

**Issue by hussainanjar** [double16/grails-cookie-session#4]
It throws error when `setsecure` is set to **true** but works when it is set to **false**

Also, springsecurity support is enabled.

```
java.lang.reflect.UndeclaredThrowableException: null 
    at com.sun.proxy.$Proxy104.execute(Unknown Source) 
    at com.esotericsoftware.kryo.pool.KryoPoolQueueImpl.run(KryoPoolQueueImpl.java:58) 
    at sun.reflect.GeneratedMethodAccessor227.invoke(Unknown Source) 
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
    at java.lang.reflect.Method.invoke(Method.java:498) 
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrap.invoke(PojoMetaMethodSite.java:213) 
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56) 
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) 
    at grails.plugin.cookiesession.KryoSessionSerializer.deserialize(KryoSessionSerializer.groovy:92) 
    at grails.plugin.cookiesession.SessionSerializer$deserialize$0.call(Unknown Source) 
    at grails.plugin.cookiesession.CookieSessionRepository.deserializeSession(CookieSessionRepository.groovy:492) 
    at grails.plugin.cookiesession.CookieSessionRepository$deserializeSession$2.callCurrent(Unknown Source) 
    at grails.plugin.cookiesession.CookieSessionRepository.restoreSession(CookieSessionRepository.groovy:353) 
    at grails.plugin.cookiesession.SessionRepositoryRequestWrapper.restoreSession(SessionRepositoryRequestWrapper.groovy:51) 
    at grails.plugin.cookiesession.CookieSessionFilter.doFilterInternal(CookieSessionFilter.groovy:77)
```

**Comment by double16** [comment]
I'm having a difficult time reproducing the error. Which version of Grails? Can you paste the portion of application.yml or application.groovy that configures this plugin? Leave out the secret key.

Are you specifying a secret key? You will need to do this for the session to work across multiple nodes or restarting your app.

If you clear cookies and then use the site, do you still get this error?

**Comment by double16** [comment]
Closing due to lack of response
